version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "dominik.shp@googlemail.com"
      PGADMIN_DEFAULT_PASSWORD: "Ho3d38tXSQD6"
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d
      - ${NODE_APP_PATH}:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodejs

