version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:81"
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d
      - ${NODE_APP_PATH}:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodejs

