name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        PORT: ${{ secrets.SERVER_PORT }}
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p $PORT $HOST >> ~/.ssh/known_hosts
        ssh -p $PORT $USER@$HOST 'cd /home/wolfram-backend && git pull && docker-compose -f docker-compose.prod.yml down && cd dev_prod && ./startup_with_clean_all.sh'
